name: Release

on:
  push:
    branches: [main]

jobs:
  release-plz:
    uses: ryanclark/workflows/.github/workflows/rust-release-plz.yml@v1
    with:
      app-id: "3903999"
    secrets:
      APP_KEY: ${{ secrets.RELEASE_PLZ_APP_KEY }}
